bu: 
  hu:
    name: HU
    company_code: 0522
    sales_org: 2800
  gr: 
    name: GR
    commpany_code: 0450
    sales_org: 1200
  pl: 
    name: PL 
    company_code: 0563 
    sales_org: 6100
  ro: 
    name: RO 
    company_code: 0580
    sales_org : 9100
  bg: 
    name: BG 
    company_code: 0428
    sales_org: 4900
  ie: 
    name: IE 
    company_code: 
      - 0491
      - 0480
    sales_org: 
      - 7800
      - 7900
application:        
  app_name: SEGMEX2_DATAMESH
  data_eng_f: DE
  data_sc_f: DS
  data_udm_f: UDM
  version: v1 
  case: 
    - PVO
    - AE
    - VFR
    - MS
mnt_point:
  adl_root_path_gen1: mnt
  adl_root_path_gen2: /mnt/datalake_gen2/
cloud:
  layers:
    l1_name: db_prod_${app_name}_${data_eng_f}_l1
    l2_name: db_prod_${app_name}${data_eng_f}_l2
    l3_name: db_prod_${app_name}_${data_eng_f}_l3
    l4_name: db_prod_${app_name}_${data_sc_f}_l4
  models:
    models_name: db_app_${app_name}_${data_sc_f}_models
    gold_name:   db_app_${app_name}_${data_sc_f}_gold
  databrick:
    dbname_l1: ${current_country_code}_${l1_name}
    dbname_l2: ${current_country_code}_${l2_name}
    dbname_l3: ${current_country_code}_${l3_name}
  dest_filepath: 
    adlpath_l0:  dbfs:${adl_root_path_gen2}cchbc/development/ACN/DataMesh/DE/L1/${CAPS_CC}/
    adlpath_l1:  dbfs:${adl_root_path_gen2}cchbc/development/ACN/DataMesh/DE/L1/CA/
    adlpath_l2:  dbfs:${adl_root_path_gen2}cchbc/development/ACN/DataMesh/DE/L2/${CAPS_CC}/
    adlpath_udm: dbfs:${adl_root_path_gen2}cchbc/development/ACN/DataMesh/DE/UDM/${CAPS_CC}/ 
data_sources:
  Customer_MD:
    source: cch_bw
    dm: md
    filepath: ca_0_cus03_customer
    flag: normal
  Trade_Channel: 
    source: cch_bw
    dm: md
    filepath: ca_ctrc01_trade_channel
    flag: normal
  Material_MD: 
    source: cch_bw
    dm: md
    filepath: ca_0_mat03_material
    flag: normal 
  MATERIAL_2: 
    source: cch_bw
    dm: md
    filepath: ca_matsv1_material
    flag: normal 
  Holiday_Calendar:
    source: cch_bw
    dm: md
    filepath: ca_holcal_holiday_calendar
    flag: normal 
  SKU_Conversion: 
    source: cch_bw
    dm: md
    filepath: ca_mm_09_sku_conversion
    flag: normal 
  CDE_Customer_Coverage": 
    source: cch_bw
    dm: md
    filepath: ca_cam015_cde_doors
    flag: normal 
  CDE_Door_Health: 
    source: cch_bw
    dm: md
    filepath: ca_cam124
    flag: normal 
  Strike_Rate: 
    source: cch_bw
    dm: md
    filepath: cafsm0491_visit_order_strike_rate
    flag: normal 
  Price_List: 
    source: cch_bw
    dm: md
    filepath: ca_co012_price_list
    flag: normal 
  Sales_DI : 
    source: cch_bw
    dm: md
    filepath: ca_fsm003_sales_direct_indirect
    flag: normal 
  call_center : 
    source: cch_bw
    dm: md
    filepath: ca_sd_11_m_sales_combined
    flag: normal 
  Suggestions_Orders : 
    source: cch_bw
    dm: md
    filepath: ca_qu_16_m_suggested_orders_compliance
    flag: normal 
  weather_future_long_range: 
    source: weather
    dm: trend
    filepath: future_long_range
    flag: normal 
  weather_future_short_range: 
    source: weather
    dm: trend
    filepath: future_short_range
    flag: normal 
  weather_history_long_range: 
    source: weather
    dm: trend
    filepath: history_long_range
    flag: normal 
  weather_history_short_range: 
    source: weather
    dm: trend
    filepath: history_short_range
    flag: normal 
  station_loc_md : 
    source: weather
    dm: trend
    filepath: station_loc_md
    flag: normal 
  fac_calender : 
    source: cch_bw
    dm: md
    filepath:  ca_faccal_calendar
    flag: normal 
  Customer_Visit_Data: 
    source: cch_bw
    dm: md
    filepath: ca_fsm044_visit_frequency
    flag: normal 
  CRM_Activities: 
    source: cch_bw
    dm: md
    filepath: ca_crm01_m_visits
    flag: normal 
  CDE_Door_Openings: 
    source: cch_bw
    dm: md
    filepath: ca_cam123_door_openings 
    flag: normal 
  RED_Availability: 
    source: cch_bw
    dm: md
    filepath: ca_fsm117_red_availability
    flag: normal 
  Red_IndexTd: 
    source: cch_bw
    dm: md
    filepath: ca_red003_red_index_td
    flag: normal 
  RED_Index: 
    source: cch_bw
    dm: md
    filepath: ca_fsm05_n_red_index
    flag: normal 
  RED_Cooler: 
    source: cch_bw
    dm: md
    filepath: ca_fsm121_red_coolers
    flag: normal 
  RED_Displays: 
    source: cch_bw
    dm: md
    filepath: ca_fsm118_red_displays
    flag: normal 
  RED_Index_Benchmark: 
    source: cch_bw
    dm: md
    filepath: ca_fsm110_red_index_benchmark
    flag: normal 
  demographic: 
    source: trade_area_analysis
    dm: {cc}
    filepath: 
    flag: special_treatment
  COPA : 
    source: cch_bw
    dm: fm
    filepath: ca_pa_200_copa_full
    flag: normal 
  Customer_Payment:
    source: cch_bw
    dm: fm
    filepath: ca_cm015_customer_payment_history
    flag: sent_to_curated
  sellout_dunhumby_fact_data: 
    source: sellout
    dm: ${cc}
    filepath: normal 
    flag:  special_treatment
  sellout_dunhumby_summary": 
    source: sellout
    dm: ${cc}
    filepath: 
    flag: special_treatment
  sellout_eyc_coke_data": 
    source: sellout
    dm: ${cc}
    filepath:
    flag: special_treatment
  sellout_eyc_summary": 
    source: sellout
    dm: ${cc}
    filepath: 
    flag: special_treatment
  sellout_talysis_aplegreen": 
    source: sellout
    dm: ${cc}
    filepath:
    flag: special_treatment
  sellout_talysis_bwg": 
    source: sellout
    dm: ${cc}
    filepath: ca_cm015_customer_payment_history
    flag: special_treatment
  sellout_talysis_summary": 
    source: sellout
    dm: ${cc}
    filepath:
    flag: special_treatment